data: 
  root: ./data/
  videos: ./data/videos/
  frames: ./data/frames/
  labelled_frames: ./data/labelled/
  image_fmt: .png

game: Valorant
spotify:
  client_id: ${env:CLIENT_ID, 0}
  client_secret: ${env:CLIENT_SECRET, 0}
  redirect_uri: ${env:REDIRECT_URI, 0}
  username: ${env:SPOTIFY_USERNAME, 0}
  scope: user-modify-playback-state
  quiet_pct: 50

env:
  client_id: CLIENT_ID
  client_secret: CLIENT_SECRET
  redirect_uri: REDIRECT_URI
  username: SPOTIFY_USERNAME

states_per_class: ???
classes: ???
model: ???